USE Product_Main
GO
CREATE TABLE Users
(
	    Id bigint Primary KEY IDENTITY(1,1) NOT NULL,
        FirstName nvarchar NOT NULL,
        LastName nvarchar NOT NULL,
        FullName nvarchar NOT NULL,
        LoginName nvarchar NOT NULL,
        IsWindowsAuthenticated bit NOT NULL,
        Password nvarchar NOT NULL,
        PhoneNumber nvarchar ,
        FaxNumber nvarchar,
        PhoneExtensionNumber nvarchar,
        Email nvarchar NOT NULL,
        IsEmailNotificationAllowed bit NOT NULL,
        LoginEffectiveDate date NOT NULL,
        LoginExpiryDate date,
        IsLoginBlocked bit,
        IsAdminBlocked bit,
		LoginBlockedTime	datetimeoffset,
        ForcePasswordReset bit,
        CreationDate date,
        ActivationDate date,
        DeactivationDate date,
        CanLogin bit,
        LoginFailureCounter int,
        ApprovalStatus nvarchar,
        Title nvarchar,
        CreatedById bigint,
        CreatedTime datetimeoffset NOT NULL,
        UpdatedById bigint,
        UpdatedTime datetimeoffset,
        IsFullAccess bit,
        DefaultBusinessUnitId bigint,
        AdminUserId bigint,
        IsFactorAuthenticationEnabled bit,
        MultiFactorAuthenticationId bit,
        ContractId bit,
        ExternalUserId nvarchar,
        DomainId bigint,
);